### PR TITLE
Fit and finish updates

### PR DESCRIPTION
**Pull request by FrankTaylorLieder**
Hi, I've recently used this crate to help with a Tube API personal project I've been working on. Thanks for creating it!

To make the library easier to use, I've made a few small changes to a fork and propose merging them back upstream.

Changes:

- Add `std::error::Error` trait to `request::Error` to make it easier to consume, e.g. with anyhow.
- Derive default values to `Arrivals` struct as I've seen the TFL API not return certain fields.
  - I thought this was better than making these fields optional. Less code churn.
- Enable to/from string for LineID.
- Fix the `LineID::line()` mapping for _And_ lines to match the API's expected ID strings.
  - E.g. `HammersmithAndCity` -> `Hammersmith-City`
  - Note: I've only done this for Tube lines.

Let me know if you are open to taking these changes. I am happy to make small changes if needed.

### CODE REVIEW

**Comment by ishantanu** [comment]
Hi @FrankTaylorLieder, thanks for creating the PR. I am happy to merge these changes. Also, would you be able to modify the API version in the test as part of this PR? It looks like the API version was updated to `master.5892`. If you can make this small change, the build will be successful.

**Comment by FrankTaylorLieder** [comment]
Thanks for wanting to take the changes.

I've fixed the test and added one to demonstrate the "And" station ID fix.

It might be good to test all LineIDs. To do that we'll need to record the route.name for each LineID. If I were to implement that I'd use strum's EnumProperty to record the LineID and Display Name for each LineID. Should I go ahead to do it?

**Comment by ishantanu** [comment]
Yes, please, that would be great. Thanks a lot for the contributions.

**Comment by FrankTaylorLieder** [comment]
I've revamped the LineID enum to use strum to help with Display and ID mappings. Mostly the line enum name, display and ID are all the same, so there is no need to supply all three. Instead we can just override the display name or ID as needed to match TFL's values.

I added a test to try out all LineIDs, but this takes too long to run. So instead we only test LineIDs that have differing display and IDs.

I would be able to batch the ID tests to reduce the number of API calls, however the routes_by_line call only accepts a single result (even through you can request multiple lines, and the backend API supports multiple lines). I have not investigated this further.

**Comment by FrankTaylorLieder** [comment]
Next update. I've looked at another way to validate the LineIDs, using the `.routes()` call. See: `confirm_all_line_ids()` test. This test only fails if a LineID/name does not match. It does not fail if we are missing a LineID, or have items that are no longer used.

This test shows that the current LineIDs do not include most of the bus routes. There are also some IDs which are no longer used by TFL.

On reflection, why do we fix the LineIDs in the wrapper? These are constantly evolving, so we'll always be playing catch up to ensure the wrapper is up-to-date. Why not make LineIDs "soft" - I.e. the caller provides the ID and name. We can provide a helper function that enumerates the IDs (like the test does).

As far as this PR goes, we can probably drop the `confirm_all_line_ids` test. Keep the changes for the current LineID enum which align the IDs and names with the API. Maybe provide a utility tool to validate the LineID enum against `routes()` which we can run manually periodically to ensure LineID is up-to-date.

Longer term, moving to a "soft" LineID would make maintenance better and ensure users of the library are not waiting on updates to enable new or modified LineIDs. This would be a breaking change so would have to be managed.

Let me know if I have misunderstood anything, and if you agree with the proposal above.

**Comment by FrankTaylorLieder** [comment]
I have removed the full LineID test and replaced it with a command line test utility to report on the differences between LineID and the API routes(). The utility reports on which IDs are missing, which have mismatched names and which are not longer in the API routes.

**Comment by FrankTaylorLieder** [comment]
I've finalised the PR based on comments above. Anything else before I mark is ready for review?

**Comment by ishantanu** [comment]
LGTM

**Review by ishantanu — APPROVED** [review]

**Comment by FrankTaylorLieder** [comment]
Thanks!

**Pull request merged**
